# Generated by Django 5.1.1 on 2024-10-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_info', '0002_movielist_streamingplatform_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingplatform',
            name='about',
            field=models.TextField(max_length=200),
        ),
    ]
