# Generated by Django 5.1.1 on 2024-10-02 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_info', '0003_alter_streamingplatform_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movielist', to='movie_info.streamingplatform'),
            preserve_default=False,
        ),
    ]
