# Generated by Django 5.1.1 on 2024-10-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_info", "0006_review_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="movielist",
            name="avg_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="movielist",
            name="number_rating",
            field=models.IntegerField(default=0),
        ),
    ]
